// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcR9luATPj8NA05Yc5OdHlaoRxMnkGLhs',
    appId: '1:335637872086:web:24d87fcfde4a1b44b03877',
    messagingSenderId: '335637872086',
    projectId: 'kutuphaneyonetimi-278ea',
    authDomain: 'kutuphaneyonetimi-278ea.firebaseapp.com',
    storageBucket: 'kutuphaneyonetimi-278ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP9AEoSi52KHVVPrMX3MkVnMO18DCYT3U',
    appId: '1:335637872086:android:c5bd20912b1b1a42b03877',
    messagingSenderId: '335637872086',
    projectId: 'kutuphaneyonetimi-278ea',
    storageBucket: 'kutuphaneyonetimi-278ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhIQguqC-q2LYF4agYtwepQhf38ZZBCz8',
    appId: '1:335637872086:ios:067cd2ae094871f8b03877',
    messagingSenderId: '335637872086',
    projectId: 'kutuphaneyonetimi-278ea',
    storageBucket: 'kutuphaneyonetimi-278ea.appspot.com',
    iosBundleId: 'com.example.ders3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhIQguqC-q2LYF4agYtwepQhf38ZZBCz8',
    appId: '1:335637872086:ios:6122ca42ffcaedd2b03877',
    messagingSenderId: '335637872086',
    projectId: 'kutuphaneyonetimi-278ea',
    storageBucket: 'kutuphaneyonetimi-278ea.appspot.com',
    iosBundleId: 'com.example.ders3.RunnerTests',
  );
}
